# Generated by Django 3.0.3 on 2020-06-02 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='pincode',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.TextField(max_length=1),
        ),
    ]
